cluster:
  mkdir -p results/slurm_logs/{rule} &&
  sbatch
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.time}
    --job-name=smk-{rule}-{wildcards}
    --output=results/slurm_logs/{rule}/{rule}-{wildcards}-%j.out
    --error=results/slurm_logs/{rule}/{rule}-{wildcards}-%j.err
    --parsable
default-resources:
  - time="02:00:00"
  - mem_mb=2300
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 50
local-cores: 1
latency-wait: 120
cores: 960
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-envmodules: True
rerun-trigger: mtime
cluster-status: status-sacct-robust.sh
cluster-cancel: scancel
cluster-cancel-nargs: 4000






set-threads:
  map_reads: 8
  multiqc_raw: 2
  mark_duplicates: 2
  angsd_paralog_prep: 10
  angsd_raw_SNP: 8
  ngsParalog_manhattan: 2
  angsd_canonical_SNP: 8
set-resources:
  trim_reads:
    time: "03:00:00"
  multiqc_raw:
    mem_mb: 6900
    time: "04:00:00"
  map_reads:
    mem_mb: 23000
    time: "143:59:00"
    threads: 8
  mark_duplicates:
    mem_mb: 13800
    time: "47:59:00"
  angsd_paralog_prep:
    mem_mb: 13800
    time: "47:59:00"
    threads: 10
  extract_read_counts:
    mem_mb: 4600
    time: "11:59:00"
    threads: 2
  ngsPara_hap1_scaffold_1:
    mem_mb: 6900
    time: "47:59:00"
  ngsPara_hap2_scaffold_1:
    mem_mb: 6900
    time: "47:59:00"
  angsd_raw_SNP:
    mem_mb: 13800
    time: "47:59:00"
    threads: 8
  ngsParalog_hap1:
    mem_mb: 6900
    time: "47:59:00"
  ngsParalog_hap2:
    mem_mb: 6900
    time: "47:59:00"
  ngsParalog_false_pos:
    mem_mb: 13800
    time: "2:00:00"
  ngsParalog_manhattan:
    mem_mb: 13800
    time: "2:00:00"
    threads: 2
  angsd_canonical_SNP:
    mem_mb: 13800
    time: "47:59:00"
    threads: 8